# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 23:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isInstructor', models.BooleanField(default=False)),
                ('isTutor', models.BooleanField(default=False)),
                ('isStudent', models.BooleanField(default=False)),
                ('isAdmin', models.BooleanField(default=False)),
                ('school', models.CharField(max_length=80)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='tutorApp.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('subject', models.CharField(max_length=30)),
                ('section_id', models.IntegerField(default=0)),
                ('instructor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructing', to='tutorApp.Profile')),
                ('students', models.ManyToManyField(blank=True, related_name='classes', to='tutorApp.Profile')),
                ('tutors', models.ManyToManyField(blank=True, related_name='tutoring', to='tutorApp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('startSession', models.DateTimeField()),
                ('endSession', models.DateTimeField()),
                ('attending', models.ManyToManyField(blank=True, related_name='sessionsAttending', to='tutorApp.Profile')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessionsCreated', to='tutorApp.Profile')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorApp.Section')),
            ],
        ),
    ]
