# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-31 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
